version: '3'

services:

  nginx:
    image: fsouza/docker-ssl-proxy
    restart: always
    ports:
      - 443:443
    environment:
      DOMAIN: ec2-54-165-9-180.compute-1.amazonaws.com
      TARGET_PORT: 80
      TARGET_HOST: www
      SSL_PORT: 443
    volumes: 
      - "./certs"
    networks:
      - progetto_cloud

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: progetto_cloud
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports: 
      - 3306:3306
    networks:
      - progetto_cloud

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - progetto_cloud

  www:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
   ## ports:
   ##   - 80:80
   ##  - 443:443
    networks: 
      - progetto_cloud

networks:
  progetto_cloud:
    driver: bridge